In [1]:
import pandas as pd
import os
import math      
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt 
import time
import warnings 
import seaborn as sns 
warnings.filterwarnings('ignore')

In [2]:
B_data=pd.read_csv("../../dataSet/B_data_time.csv")
T_data=pd.read_csv("../../dataSet/T_data_time.csv")

In [3]:
B_data[["BARCODE_INDEX","Volume(%)","Height(um)","Area(%)","OffsetX(mm)"]]

         BARCODE_INDEX  Volume(%)  Height(um)  Area(%)  OffsetX(mm)
0                13611     98.832     106.662   92.660        0.005
1                13611     95.402     100.189   95.222        0.000
2                13611    103.047     111.748   92.214       -0.011
3                13611    105.500     117.418   89.850        0.000
4                13611    103.741     117.714   88.129       -0.008
...                ...        ...         ...      ...          ...
6557875          44197    113.166     110.799  102.136       -0.005
6557876          44197    131.565     120.853  108.864        0.011
6557877          44197    124.038     124.045   99.994       -0.015
6557878          44197     92.592      88.401  104.741       -0.003
6557879          44197    108.823      99.683  109.168        0.001

[6557880 rows x 5 columns]